/**********************************************************************************************************/
/***** AUTOGENERATED from git@github.deere.com:Construction-BatteryElectricVehicle/ExternalMaster.git *****/
/**********************************************************************************************************/

#include "CAN_11Bit_HashValue.h"
#include "CAN_11Bit_Callback.h"


/* Recall that Relevancy_Table_Item struct has members:
*		- UInt8_T relevancy_val
*		- UInt16_T intended_id
*		- void (* cb)(struct Std_CAN_Queeu_Item_S * item) */

const struct Relevancy_Table_Item RELEVANCY_HASH_TABLE[STD_QUEUE_HASH_NUM] = 
{
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	1,		288 ,		VoltStatsBlock_CellVoltage_Pack1_Callback	},
	{	1,		289 ,		VoltStatsBlock_CellVoltage_Pack2_Callback	},
	{	1,		290 ,		VoltStatsBlock_CellVoltage_Pack3_Callback	},
	{	0,		0   ,		NULL	},
	{	1,		576 ,		TempCoolantOut_Pack1_Callback	},
	{	1,		577 ,		TempCoolantOut_Pack2_Callback	},
	{	1,		578 ,		TempCoolantOut_Pack3_Callback	},
	{	1,		224 ,		Protections_ModFaults_Pack1_Callback	},
	{	1,		225 ,		Protections_ModFaults_Pack2_Callback	},
	{	1,		226 ,		Protections_ModFaults_Pack3_Callback	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	1,		160 ,		Status_BMSContactorState_Pack1_Callback	},
	{	1,		161 ,		Status_BMSContactorState_Pack2_Callback	},
	{	1,		162 ,		Status_BMSContactorState_Pack3_Callback	},
	{	0,		0   ,		NULL	},
	{	1,		448 ,		IsolationStatus_Pack1_Callback	},
	{	1,		449 ,		IsolationStatus_Pack2_Callback	},
	{	1,		450 ,		IsolationStatus_Pack3_Callback	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	1,		608 ,		TempCell_CellTemp_Pack1_Callback	},
	{	1,		609 ,		TempCell_CellTemp_Pack2_Callback	},
	{	1,		610 ,		TempCell_CellTemp_Pack3_Callback	},
	{	0,		0   ,		NULL	},
	{	1,		896 ,		StateOfEnergy_SOC_Pack1_Callback	},
	{	1,		897 ,		StateOfEnergy_SOC_Pack2_Callback	},
	{	1,		898 ,		StateOfEnergy_SOC_Pack3_Callback	},
	{	1,		544 ,		TempCoolantIn_Pack1_Callback	},
	{	1,		545 ,		TempCoolantIn_Pack2_Callback	},
	{	1,		546 ,		TempCoolantIn_Pack3_Callback	},
	{	1,		192 ,		Protections_BMSFaults_Pack1_Callback	},
	{	1,		193 ,		Protections_BMSFaults_Pack2_Callback	},
	{	1,		194 ,		Protections_BMSFaults_Pack3_Callback	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	1,		128 ,		Vitals_PackVoltageCurrent_Pack1_Callback	},
	{	1,		129 ,		Vitals_PackVoltageCurrent_Pack2_Callback	},
	{	1,		130 ,		Vitals_PackVoltageCurrent_Pack3_Callback	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	0,		0   ,		NULL	},
	{	1,		704 ,		StressEst_Pack1_Callback	},
	{	1,		705 ,		StressEst_Pack2_Callback	},
	{	1,		706 ,		StressEst_Pack3_Callback	},
	{	1,		352 ,		PowerLimits_MaxChgDschgCurr_Pack1_Callback	},
	{	1,		353 ,		PowerLimits_MaxChgDschgCurr_Pack2_Callback	},
	{	1,		354 ,		PowerLimits_MaxChgDschgCurr_Pack3_Callback	},

};