/**********************************************************************************************************/
/***** AUTOGENERATED from git@github.deere.com:Construction-BatteryElectricVehicle/ExternalMaster.git *****/
/**********************************************************************************************************/

#ifndef STD_CAN_HASH_VALUE_H
#define STD_CAN_HASH_VALUE_H

#define STD_QUEUE_HASH_NUM	71

#endif		// STD_CAN_HASH_VALUE_H