/**********************************************************************************************************/
/***** AUTOGENERATED from git@github.deere.com:Construction-BatteryElectricVehicle/ExternalMaster.git *****/
/**********************************************************************************************************/

#ifndef EXM_CALLBACKS_H
#define EXM_CALLBACKS_H

#include "HWCONFIG.H"
#include "CAN_StandardCAN_DS.h"

extern struct Std_CAN_Queue_Item_S;


/** Function Declarations **/
void VoltStatsBlock_CellVoltage_Callback(struct Std_CAN_Queue_Item_S * item);

void TempCoolantOut_Callback(struct Std_CAN_Queue_Item_S * item);

void Protections_BMSFaults_Callback(struct Std_CAN_Queue_Item_S * item);

void Status_BMSContactorState_Callback(struct Std_CAN_Queue_Item_S * item);

void IsolationStatus_Callback(struct Std_CAN_Queue_Item_S * item);

void TempCell_CellTemp_Callback(struct Std_CAN_Queue_Item_S * item);

void StateOfEnergy_SOC_Callback(struct Std_CAN_Queue_Item_S * item);

void TempCoolantIn_Callback(struct Std_CAN_Queue_Item_S * item);

void Vitals_PackVoltageCurrent_Callback(struct Std_CAN_Queue_Item_S * item);

void StressEst_Callback(struct Std_CAN_Queue_Item_S * item);

void PowerLimits_MaxChgDschgCurr_Callback(struct Std_CAN_Queue_Item_S * item);



#endif		// EXM_CALLBACKS_H