/**********************************************************************************************************/
/***** AUTOGENERATED from git@github.deere.com:Construction-BatteryElectricVehicle/ExternalMaster.git *****/
/**********************************************************************************************************/

#ifndef CAN_11BIT_CALLBACKS_H
#define CAN_11BIT_CALLBACKS_H

#include "HWCONFIG.H"
#include "CAN_11Bit_Queues.h"

extern struct Std_CAN_Queue_Item_S;


/** Function Declarations **/
void Vitals_PackVoltageCurrent_Pack1_Callback(struct Std_CAN_Queue_Item_S * item);

void Vitals_PackVoltageCurrent_Pack2_Callback(struct Std_CAN_Queue_Item_S * item);

void Vitals_PackVoltageCurrent_Pack3_Callback(struct Std_CAN_Queue_Item_S * item);

void Status_BMSContactorState_Pack1_Callback(struct Std_CAN_Queue_Item_S * item);

void Status_BMSContactorState_Pack2_Callback(struct Std_CAN_Queue_Item_S * item);

void Status_BMSContactorState_Pack3_Callback(struct Std_CAN_Queue_Item_S * item);

void StateOfEnergy_SOC_Pack1_Callback(struct Std_CAN_Queue_Item_S * item);

void StateOfEnergy_SOC_Pack2_Callback(struct Std_CAN_Queue_Item_S * item);

void StateOfEnergy_SOC_Pack3_Callback(struct Std_CAN_Queue_Item_S * item);

void PowerLimits_MaxChgDschgCurr_Pack1_Callback(struct Std_CAN_Queue_Item_S * item);

void PowerLimits_MaxChgDschgCurr_Pack2_Callback(struct Std_CAN_Queue_Item_S * item);

void PowerLimits_MaxChgDschgCurr_Pack3_Callback(struct Std_CAN_Queue_Item_S * item);

void VoltStatsBlock_CellVoltage_Pack1_Callback(struct Std_CAN_Queue_Item_S * item);

void VoltStatsBlock_CellVoltage_Pack2_Callback(struct Std_CAN_Queue_Item_S * item);

void VoltStatsBlock_CellVoltage_Pack3_Callback(struct Std_CAN_Queue_Item_S * item);

void TempCell_CellTemp_Pack1_Callback(struct Std_CAN_Queue_Item_S * item);

void TempCell_CellTemp_Pack2_Callback(struct Std_CAN_Queue_Item_S * item);

void TempCell_CellTemp_Pack3_Callback(struct Std_CAN_Queue_Item_S * item);

void StressEst_Pack1_Callback(struct Std_CAN_Queue_Item_S * item);

void StressEst_Pack2_Callback(struct Std_CAN_Queue_Item_S * item);

void StressEst_Pack3_Callback(struct Std_CAN_Queue_Item_S * item);

void IsolationStatus_Pack1_Callback(struct Std_CAN_Queue_Item_S * item);

void IsolationStatus_Pack2_Callback(struct Std_CAN_Queue_Item_S * item);

void IsolationStatus_Pack3_Callback(struct Std_CAN_Queue_Item_S * item);

void Protections_BMSFaults_Pack1_Callback(struct Std_CAN_Queue_Item_S * item);

void Protections_BMSFaults_Pack2_Callback(struct Std_CAN_Queue_Item_S * item);

void Protections_BMSFaults_Pack3_Callback(struct Std_CAN_Queue_Item_S * item);

void Protections_ModFaults_Pack1_Callback(struct Std_CAN_Queue_Item_S * item);

void Protections_ModFaults_Pack2_Callback(struct Std_CAN_Queue_Item_S * item);

void Protections_ModFaults_Pack3_Callback(struct Std_CAN_Queue_Item_S * item);

void TempCoolantIn_Pack1_Callback(struct Std_CAN_Queue_Item_S * item);

void TempCoolantIn_Pack2_Callback(struct Std_CAN_Queue_Item_S * item);

void TempCoolantIn_Pack3_Callback(struct Std_CAN_Queue_Item_S * item);

void TempCoolantOut_Pack1_Callback(struct Std_CAN_Queue_Item_S * item);

void TempCoolantOut_Pack2_Callback(struct Std_CAN_Queue_Item_S * item);

void TempCoolantOut_Pack3_Callback(struct Std_CAN_Queue_Item_S * item);



#endif		// CAN_11BIT_CALLBACKS_H